name: Keep CDN File Alive

on:
  push:
    branches:    
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  keep-alive:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Output IP
        run: |
             curl -s "ip.sb"
      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache Dependences
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./.github/workflows/build.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependences
        run: pip install httpx websockets
      - name: KeepAlive
        run: python ./.github/workflows/keepalive.py