name: Keep CDN File Alive

on:
  push:
    branches:    
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: keep-alive
        run: |
            array=()
            mapfile -d $'\0' array < <(find . -type f -not -path "./.git/*" -not -path "./.github/*" -print0)
            for i in  ${array[@]}
            do
              for _ in {1..5}
              do
                  echo 'https://cdn.jsdelivr.net/gh/rcsupermanjob/Storage@latest/'${i: 2}
                curl -sIL -w "%{http_code} %{time_total}\n" -o /dev/null 'https://cdn.jsdelivr.net/gh/rcsupermanjob/Storage@latest/'${i: 2} \
                -H 'authority: cdn.jsdelivr.net' \
                -H 'sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not\\A\"Brand";v="99"' \
                -H 'sec-ch-ua-mobile: ?1' \
                -H 'upgrade-insecure-requests: 1' \
                -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Mobile Safari/537.36' \
                -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
                -H 'sec-fetch-site: same-origin' \
                -H 'sec-fetch-mode: navigate' \
                -H 'sec-fetch-user: ?1' \
                -H 'sec-fetch-dest: document' \
                -H 'referer: https://cdn.jsdelivr.net/gh/rcsupermanjob/Storage/' \
                -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
                --compressed
              done
              sleep 3
            done