name: Keep CDN File Alive

on:
  push:
    branches:    
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: keep-alive
        run: |
            array=()
            mapfile -d $'\0' array < <(find . -not -path "./.git/*" -not -path "./.github/*" -print0)
            for i in ${array[@]}
            do
                echo $i
            done