name: Keep CDN File Alive

on:
  push:
    branches:    
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  issue:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.files }}
    steps:
      - uses: actions/checkout@v1
      - name: Get Files
        id: get-files
        run: |
            echo ::set-output name=files::$(find . -not -path "./github/*" -not -path "./git/*")
      - name: output
        run: echo "The result is ${{ steps.get-files.outputs.files }}"
