name: Keep CDN File Alive

on:
  push:
    branches:    
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache Dependences
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependences
        run: pip install httpx websockets
      - name: KeepAlive
        run: python ./.github/workflows/keepalive.py