name: Create Release

on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create-release
        uses: release-drafter/release-drafter@v5
        with:
          name: storage
          perrelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}